# Generated by Django 4.2.7 on 2024-05-20 12:34

from django.db import migrations, models
import voice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('files', models.FileField(upload_to=voice.models.get_file_path)),
                ('file_name', models.TextField()),
                ('file_time', models.TextField()),
                ('real_file_name', models.TextField()),
            ],
        ),
    ]
