# Generated by Django 4.2.4 on 2024-05-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'verbose_name_plural': 'Файлы записей'},
        ),
    ]
